openapi: '3.0.3'

info: 
  title: OpenAPI Specification for Matveckan
  description: API specification document for the Matveckan system
  version: '1.0.0'
  contact:
    name: Patric Bergkvist
    email: dev@matveckan.se
    url: http://www.patricbergkvist.com

servers: 
  - url: http://localhost:44333/api/v1
    description: Production server

externalDocs:
  description: More information about Matveckan API
  url: http://www.test.nu

tags:
  - name: users
    description: Operations for users
  - name: recipes
    description: Operations for recipes

paths:
  /users:
    summary: Operations for users
    description: Contains all operations for users
    get:
      tags: 
        - users
      summary: Get all users
      description: Returns a list of all users
      operationId: getUsers
      responses:
        '200':
          description: Successfully returned all users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          description: Bad Request
          $ref: "#/components/responses/4xxResponse"
        '500':
          description: Internal server error
          $ref: "#/components/responses/5xxResponse"
    post:
      tags:
        - users
      summary: Add new user
      description: Adds a new user to the system
      operationId: addUser
      requestBody:
        description: Adds a new user to the system
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: Successfully added user to the system
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          description: Bad request
          $ref: "#/components/responses/4xxResponse"
        '500':
          description: Internal server error
          $ref: "#/components/responses/5xxResponse"

  /recipes:
    summary: Operations for recipes
    description: Contains all operations of recipes
    get:
      tags:
        - recipes
      summary: Gets all recipes
      description: Returns a list of all recipes
      operationId: getRecipes
      responses:
        '200':
          description: Successfully returned all recipes
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recipe"
        '4XX':
          description: Bad request
          $ref: "#/components/responses/4xxResponse"
        '5XX':
          description: Internal server error
          $ref: "#/components/responses/5xxResponse"
  /recipes/{recipeId}:
    summary: Operations for specific recipe
    description: Contains all operations for specific recipes
    get:
      tags:
        - recipes
      summary: Gets a specific recipe based on recipeId
      description: Returns the specific recipe
      operationId: getRecipe
      responses:
        '200':
          description: Successfully returned recipe
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Recipe"
        '4XX':
          description: Bad request
          $ref: "#/components/responses/4xxResponse"
        '5XX':
          description: Internal server error
          $ref: "#/components/responses/5xxResponse"

components:
  schemas:
    User:
      type: object
      description: Represents a user entry
      properties:
        firstName:
          type: string
          description: The users first name
        lastName:
          type: string
          description: The users last name
        nickname:
          type: string
          description: The users nickname
        password:
          type: string
          description: The users password
        phoneNumber:
          type: string
          description: The users phone number
        email:
          type: string
          format: email
          description: The users email
      required:
        - nickname
        - phoneNumber
        - password
        - email
    Recipe:
      type: object
      description: Represents a recipe entry
      properties:
        id:
          type: integer
          description: Unique id for the recipe
        name:
          type: string
          description: Name of the recipe
        preparationTime: 
          type: integer
          description: Preparation time in minutes
        cookingTime:
          type: integer
          description: Cooking time in minutes
        category:
          type: string
          enum:
            - Pasta
            - Meat
            - Potato
          description: Recipe category
        portions:
          type: integer
          description: Amount of portions for the recipe
        ingredients:
          description: Ingredients for the recipe
          type: array
          items:
              $ref: "#/components/schemas/ingredient"
        instructions:
          description: Instructions for the recipe
          type: array
          items:
            $ref: "#/components/schemas/instruction"
      required:
        - name
        - preparationTime
        - cookingTime
        - category
        - portions
        - ingredients
        - instructions
    ingredient:
      type: object
      description: Represents a ingredient entry
      properties:
        unitOfMeasurement:
          description: Represents the unit of measurement for the ingredient
          type: string
          enum:
            - grams
            - milliliters
        unit:
          type: number
          format: double
          minimum: 0
          maximum: 20000
        name:
          type: string
    instruction:
      description: Represents a instruction entry
      type: object
      properties:
        stepName:
          description: Represents a step in the instruction
          type: string
      required:
        - stepName

  responses:
    4xxResponse:
      description: Bad Request
    5xxResponse:
      description: Internal server error