version: "3.9"

services:
  db:
    image: mariadb:10.5
    ports:
      - "35100:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dockerDb
      MYSQL_DATABASE: Matveckan
    restart: always
    volumes:
      - matveckan-dev-mariadb-data:/var/lib/mysql
      - matveckan-dev-mariadb-config:/etc/mysql/conf.d
  api:
    build: ./api
    ports:
      - 35103:80
  client:
    build: ./client
    ports:
      - 35104:80
  prism-mock:
    build: ./api-definition
    ports:
      - 35101:35101
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "35102:8080"
    volumes:
      - ./api-definition/matveckan.oas.yaml:/matveckan.oas.yaml
    environment:
      SWAGGER_JSON: /matveckan.oas.yaml

volumes:
  matveckan-dev-mariadb-data:
    driver: local
  matveckan-dev-mariadb-config:
    driver: local