version: "3.9"

services:
  api:
    build: ./api
    ports:
      - 4000:80
  client:
    build: ./client
    ports:
      - 5000:80
  prism-mock:
    build: ./api-definition
    ports:
      - 35101:35101
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "4012:8080"
    volumes:
      - ./api-definition/matveckan.oas.yaml:/matveckan.oas.yaml
    environment:
      SWAGGER_JSON: /matveckan.oas.yaml