name: CI Pipeline

on: [push]

jobs:
  build:
    name: Build Matveckan solution
    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore Matveckan.sln

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # - name: Test
      #   run: dotnet test --no-restore --verbosity normal