name: Run Spectral Lint on push

on:
  push:
    branches:
      - '!main'
    # paths:
    #   - 'src/api-definition/**'

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@v0.8.1
        with:
          file_glob: '/src/api-definition/matveckan.oas.yaml'
